# Nixpacks Configuration for Railway
[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"
